
MAPPED_URLS = {
	'ticket':{
		'get':'{model}s/{ticket_id}.json',
		'fetch':{
			'default':'{model}s.json',
			'view':'{relation}s/{view_id}/{model}s.json?include=users'
		},
		'put':{
			'create':'{model}s.json',
			'update':'{model}s/{id}.json'
		},
		'delete':'{model}s/{id}.json'
	},
	'audit':{
		'get':'{relation}s/{ticket_id}/{model}s/{audit_id}.json',
		'fetch':'{relation}s/{ticket_id}/{model}s.json',
	},
	'comment':{
		'fetch':'{relation}s/{ticket_id}/{model}s.json'
	},
	'ticket_metric':{
		'get':'{model}s/{ticket_metric_id}.json',
		'fetch':'{model}s.json'
	},
	'user':{
		'get':'{model}s/{user_id}.json',
		'fetch':'{model}s/show_many.json?ids={ids}',
		'put':{
			'create':'{model}s.json',
			'update':'{model}s/{id}.json'
		},
		'delete':'{model}s/{id}.json'
	},
	'group':{
		'get':'{model}s/{group_id}.json',
		'fetch':'{model}s.json',
		'put':{
			'create':'{model}s.json',
			'update':'{model}s/{id}.json'
		},
		'delete':'{model}s/{id}.json'
	},
	'group_membership':{
		'get':'{model}s/{group_membership_id}.json',
		'fetch':{
			'default':'{model}s.json',
			'user':'{relation}s/{user_id}/{model}s.json',
			'group':'{relation}s/{group_id}/memberships.json'
		},
		'delete':'{model}s/{id}.json',
		'put':{
			'create':'{model}s.json'
		},
	},
	'user_field':{
		'fetch':'{model}s.json',
		'get':'{model}s/{user_field_id}.json'
	},
	'custom_role':{
		'fetch':'{model}s.json'
	},
	'ticket_form':{
		'fetch':'{model}s.json',
		'get':'{model}s/{ticket_form_id}.json'
	},
	'ticket_field':{
		'fetch':'{model}s.json'
	},
	'view':{
		'fetch':'{model}s/compact.json',
		'get':'{model}s/{view_id}.json'
	},
	'view_count':{
		'fetch':'{relation}s/count_many.json?ids={ids}'
	},
	'identitie':{
		'fetch':'{relation}s/{user_id}/{model}s.json',
		'get':'{relation}s/{user_id}/{model}s/{identity_id}.json',
		'put':{
			'create':'{relation}s/{user_id}/{model}s.json'
		},
		'delete':'{relation}s/{user_id}/{model}s/{id}.json'
	},
	'upload':{
		'upload':'{model}s.json?filename={filename}'
	},
	'attachment':{
		'get':'{model}s/{attachment_id}.json'
	},
	'organization':{
		'get':'{model}s/{organization_id}.json',
		'fetch':'{model}s.json',
		'put':{
			'create':'{model}s.json',
			'update':'{model}s/{id}.json'
		},
		'delete':'{model}s/{id}.json'
	},
	'organization_field':{
		'fetch':'{model}s.json',
		'get':'{model}s/{organization_field_id}.json',
		'put':{
			'create':'{model}s.json',
			'update':'{model}s/{id}.json'
		}
	}
}
